'use client'

import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Cpu, Factory, FileDown, Globe2, Layers3, Mail, Menu, MoveRight, Phone, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'

type Lang = 'en' | 'zh'

type Copy = { nav: string[]; cta: string; eyebrow: string; hero: string; heroMuted: string; intro: string; sample: string; catalog: string; standard: string; global: string; rfq: string; quote: string; address: string; email: string; phone: string; metricLabels: string[]; complianceTitle: string; complianceText: string; productTitle: string; productMuted: string; formLine: string; formVolume: string; formEmail: string; formRegion: string; estimate: string; shipping: string; weight: string; dispatch: string; value: string; send: string; sent: string; footer: string }
const copy: Record<Lang, Copy> = {
  en: { nav: ['Engineering', 'SS-00259 Standard', 'Tooling Catalog', 'Global Supply'], cta: 'Request sample kit', eyebrow: '01 / The benchmark', hero: 'Optical-grade', heroMuted: 'injection molding.', intro: 'Engineered for global media and collectibles. 24 years of zero-scratch mold craft, responsible material compliance, and direct-source manufacturing.', sample: 'Claim free sample pack', catalog: 'Explore tooling library', standard: 'Compliance is not a badge.', global: 'It is the baseline.', rfq: '03 / RFQ terminal', quote: 'Let’s make\nthe first one.', address: 'No. 2 Banhu Old Street, Huangjiang Town, Dongguan, Guangdong, China', email: 'ngkeihing@126.com', phone: '+86 139 0303 5533', metricLabels: ['Years of tooling', 'Countries supplied', 'mm tolerance', 'Units / month'], complianceTitle: 'Sony Green Partner / SS-00259', complianceText: 'Laboratory-grade hazardous substance management. Export clearance for EU, Japan, and North America.', productTitle: 'Built to be handled.', productMuted: 'Made to be kept.', formLine: '01 / Packaging model', formVolume: '02 / Estimated volume', formEmail: '03 / Corporate work email', formRegion: '04 / Destination port / region', estimate: 'Live logistics estimate', shipping: 'Estimated shipping volume', weight: 'Estimated gross weight', dispatch: 'Rapid sample dispatch', value: 'Factory Direct Pricing · 0% Middleman Markup · Official CAD & DFM Feedback in 12 Hours', send: 'Send inquiry', sent: 'Inquiry received — we’ll reply from the factory within 12 hours.', footer: 'SUN LIGHT CASSETTE MANUFACTURING LIMITED' },
  zh: { nav: ['工程能力', 'SS-00259 标准', '产品目录', '全球供应'], cta: '索取样品套装', eyebrow: '01 / 行业基准', hero: '光学级', heroMuted: '注塑成型。', intro: '为全球媒体与收藏品而造。24 年零刮痕模具工艺、负责任的材料合规，以及源头工厂直供。', sample: '领取免费样品包', catalog: '探索模具目录', standard: '合规不是标签。', global: '而是基准。', rfq: '03 / 询价终端', quote: '让我们\n做出第一个。', address: '中国广东省东莞市黄江镇板湖旧街 2 号', email: 'ngkeihing@126.com', phone: '+86 139 0303 5533', metricLabels: ['模具经验年限', '供应国家', '毫米公差', '每月产能'], complianceTitle: 'Sony Green Partner / SS-00259', complianceText: '实验室级有害物质管理，满足欧盟、日本及北美出口要求。', productTitle: '经得起握持。', productMuted: '值得被珍藏。', formLine: '01 / 包装型号', formVolume: '02 / 预估数量', formEmail: '03 / 企业工作邮箱', formRegion: '04 / 目的港 / 地区', estimate: '实时物流预估', shipping: '预估运输体积', weight: '预估毛重', dispatch: '快速寄样时间', value: '工厂直供价 · 0% 中间商加价 · 12 小时内提供官方 CAD 与 DFM 反馈', send: '发送询价', sent: '询价已收到 — 工厂将在 12 小时内回复。', footer: '东莞市新辉盒带厂有限公司' },
}
const products = [['01', 'Standard Jewel Case', '10.4 mm / GPPS', 'High-gloss GPPS · engineered book-fold hinge · 1,000+ cycle fatigue resistance', Layers3], ['02', 'Slimline Case', '5.2 mm / PP', 'Ultra-thin space-saving optical tray · optimized for premium media collections', Sparkles], ['03', 'Multi-Disc Housing', 'Dual / Quad Tray', 'Modular disc trays · SD / USB integrated media organizers · export ready', Cpu], ['04', 'Collectible Brick', 'Optical-grade / GPPS', 'Acrylic-equivalent clarity · scratch-resistant snap locks for card markets', Zap]] as const
const compliance = [['Cd', '< 5ppm'], ['Pb', 'Zero Added'], ['Hg', 'Zero Added'], ['Cr⁶⁺', 'Zero Added'], ['PBB / PBDE', 'Free'], ['RoHS 2.0', '& REACH'], ['BPA', 'Free']]
const logistics: Record<string, Record<string, [string, string]>> = { 'Standard Jewel Case': { '2,000': ['1.8 CBM', '240 kg'], '10,000': ['9.0 CBM', '1,200 kg'], '50,000': ['45 CBM', '6,000 kg'], '200,000+': ['180+ CBM', '24,000+ kg'] }, 'Slimline Case': { '2,000': ['1.1 CBM', '150 kg'], '10,000': ['5.5 CBM', '750 kg'], '50,000': ['27.5 CBM', '3,750 kg'], '200,000+': ['110+ CBM', '15,000+ kg'] }, 'Multi-Disc Housing': { '2,000': ['3.0 CBM', '420 kg'], '10,000': ['15 CBM', '2,100 kg'], '50,000': ['75 CBM', '10,500 kg'], '200,000+': ['300+ CBM', '42,000+ kg'] }, 'Collectible Brick': { '2,000': ['2.4 CBM', '310 kg'], '10,000': ['12 CBM', '1,550 kg'], '50,000': ['60 CBM', '7,750 kg'], '200,000+': ['240+ CBM', '31,000+ kg'] } }

export default function Page() {
  const [lang, setLang] = useState<Lang>('en'); const t = copy[lang]; const [menuOpen, setMenuOpen] = useState(false); const [model, setModel] = useState('Standard Jewel Case'); const [volume, setVolume] = useState('10,000'); const [sent, setSent] = useState(false); const [workEmail, setWorkEmail] = useState(''); const [region, setRegion] = useState(''); const estimate = logistics[model][volume]
  return <main id="top" className="site-shell"><div className="grain" /><nav className="nav-rail"><a href="#top" className="brand"><span className="brand-mark">SL</span><span>SUN LIGHT <small>· est. 2002</small></span></a><div className="nav-links">{t.nav.map((n, i) => <a key={n} href={['#engineering', '#standard', '#tooling', '#global'][i]}>{n}</a>)}</div><div className="nav-actions"><div className="toggle"><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button><button className={lang === 'zh' ? 'active' : ''} onClick={() => setLang('zh')}>中文</button></div><a href="#quote" className="nav-cta">{t.cta}<ArrowUpRight /></a><button className="menu-button" aria-label="打开菜单" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <div className="mobile-menu">{t.nav.map((n, i) => <a key={n} href={['#engineering', '#standard', '#tooling', '#global'][i]} onClick={() => setMenuOpen(false)}>{n}</a>)}</div>}</nav>
    <section className="hero-wrap"><div className="hero-copy"><Eyebrow>{t.eyebrow}</Eyebrow><div className="status-line"><span /> CERTIFIED SONY GREEN PARTNER · UKAS · 5M/MO</div><h1>{t.hero}<br /><em>{t.heroMuted}</em></h1><p>{t.intro}</p><div className="hero-actions"><a className="button button-solid" href="#quote">{t.sample}<ArrowUpRight /></a><a className="button button-line" href="#tooling">{t.catalog}<FileDown /></a></div></div><ExplodedCase /><div className="metrics"><Metric value="24" label={t.metricLabels[0]} /><Metric value="60+" label={t.metricLabels[1]} /><Metric value="±0.05" label={t.metricLabels[2]} /><Metric value="5M+" label={t.metricLabels[3]} /></div></section>
    <section id="engineering" className="ledger-section"><div className="section-intro"><Eyebrow>{t.eyebrow}</Eyebrow><h2>{t.standard}<br /><em>{t.global}</em></h2><p>{t.complianceText}</p></div><div id="standard" className="compliance-panel"><div className="panel-head"><div><ShieldCheck /><h3>{t.complianceTitle}</h3><p>{t.complianceText}</p></div><span className="verified">● VERIFIED</span></div><div className="compliance-grid">{compliance.map(([a, b]) => <span key={a}><b>{a}</b>{b}</span>)}</div><div className="feature-row"><Feature icon={Factory} title={lang === 'en' ? 'Precision tooling' : '精密模具'} text={lang === 'en' ? 'Cleanroom molding · robotic pick & place · anti-static de-ionizing curtains.' : '洁净注塑 · 机械手取件 · 防静电离子风幕。'} /><Feature icon={Globe2} title={lang === 'en' ? 'Factory backbone' : '工厂基础能力'} text={lang === 'en' ? 'Founded 2002 · 5,000,000+ monthly capacity · direct export to 60+ countries.' : '成立于 2002 年 · 每月 5,000,000+ 产能 · 直供全球 60+ 国家。'} /></div></div></section>
    <section id="tooling" className="catalog-section"><div className="catalog-head"><Eyebrow>02 / Product architecture</Eyebrow><h2>{t.productTitle}<br /><em>{t.productMuted}</em></h2></div><div className="product-grid">{products.map(([number, title, meta, detail, Icon]) => <article className="product-card" key={number}><div className="card-top"><span>[ {number} ]</span><Icon /></div><div className="card-body"><h3>{title}</h3><p className="mono accent">{meta}</p><p>{detail}</p></div><span className="crosshair">+</span></article>)}</div></section>
    <section id="quote" className="quote-section"><div className="quote-intro"><Eyebrow>{t.rfq}</Eyebrow><h2>{t.quote}</h2><p>{t.value}</p><div className="contact-code"><span>24</span>{t.metricLabels[0]}</div></div><form className="rfq-form" onSubmit={(e) => { e.preventDefault(); setSent(true) }}><label>{t.formLine}</label><div className="model-grid">{Object.keys(logistics).map((name) => <button type="button" key={name} onClick={() => setModel(name)} className={model === name ? 'selected' : ''}>{name}</button>)}</div><label>{t.formVolume}</label><div className="select-wrap"><select value={volume} onChange={(e) => setVolume(e.target.value)}>{['2,000', '10,000', '50,000', '200,000+'].map((v) => <option key={v}>{v}</option>)}</select><ChevronDown /></div><div className="rfq-fields"><div className="field-group"><label>{t.formEmail}</label><input type="email" required value={workEmail} onChange={(e) => setWorkEmail(e.target.value)} placeholder="procurement@company.com" /></div><div className="field-group"><label>{t.formRegion}</label><input required value={region} onChange={(e) => setRegion(e.target.value)} placeholder="e.g. Los Angeles, Rotterdam, Tokyo" /></div></div><div className="estimate"><p>{t.estimate}</p><div><Stat label={t.shipping} value={estimate[0]} /><Stat label={t.weight} value={estimate[1]} /><Stat label={t.dispatch} value="24h–48h" /></div></div>{sent ? <div className="success">✓ {t.sent}</div> : <button className="submit-button" type="submit">{t.send}<MoveRight /></button>}</form></section>
    <footer id="global"><div><p className="footer-title">{t.footer}</p><p>东莞市新辉盒带厂有限公司</p><p>{t.address}</p></div><div className="footer-contact"><a href={`mailto:${t.email}`}><Mail />{t.email}</a><a href={`tel:${t.phone.replaceAll(' ', '')}`}><Phone />{t.phone}</a><span>© 2026 SUN LIGHT CASSETTE MANUFACTURING LIMITED · Sony GP · UKAS · RoHS · REACH</span></div></footer>
  </main>
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p> }
function Metric({ value, label }: { value: string; label: string }) { return <div><strong>{value}</strong><span>{label}</span></div> }
function Feature({ icon: Icon, title, text }: { icon: typeof Factory; title: string; text: string }) { return <div className="feature"><Icon /><h3>{title}</h3><p>{text}</p></div> }
function Stat({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function ExplodedCase() { return <div className="exploded" aria-label="Exploded optical enclosure illustration"><div className="datum datum-a">A–A / 01</div><div className="datum datum-b">+0.05 / GPPS</div><div className="dimension dim-v">132.0</div><div className="dimension dim-h">10.4</div><div className="assembly assembly-back" /><div className="assembly assembly-front"><span className="hinge" /><span className="disc" /></div><div className="callout callout-a">MOLD PARTING LINE</div><div className="callout callout-b">BOOK-FOLD HINGE</div><div className="axis">X&nbsp;&nbsp;&nbsp;Y&nbsp;&nbsp;&nbsp;Z</div></div>}
