'use client'

import { useState } from 'react'
import { ArrowUpRight, Check, ChevronDown, Cpu, Factory, FileDown, Globe2, Layers3, Mail, Menu, MoveRight, Phone, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'

type Lang = 'en' | 'zh'

type Copy = {
  nav: string[]; cta: string; eyebrow: string; hero: string; heroMuted: string; intro: string; sample: string; catalog: string; standard: string; global: string; rfq: string; quote: string; contact: string; address: string; email: string; phone: string; metricLabels: string[]; complianceTitle: string; complianceText: string; productTitle: string; productMuted: string; formLine: string; formVolume: string; estimate: string; shipping: string; weight: string; dispatch: string; value: string; send: string; sent: string; footer: string
}
const copy: Record<Lang, Copy> = {
  en: { nav: ['Engineering', 'SS-00259 Standard', 'Tooling Catalog', 'Global Supply'], cta: 'Request sample kit', eyebrow: '01 / The benchmark', hero: 'Optical-grade', heroMuted: 'injection molding.', intro: 'Engineered for global media and collectibles. 24 years of zero-scratch mold craftsmanship, responsible material compliance, and direct-source manufacturing.', sample: 'Claim free sample pack', catalog: 'Explore tooling library', standard: 'Compliance is not a badge.', global: 'It is the baseline.', rfq: '03 / RFQ terminal', quote: 'Let’s make\nthe first one.', contact: 'Factory contact', address: 'No. 2 Banhu Old Street, Huangjiang Town, Dongguan, Guangdong, China', email: 'ngkeihing@126.com', phone: '+86 139 0303 5533', metricLabels: ['Years of tooling', 'Countries supplied', 'mm tolerance', 'Units / month'], complianceTitle: 'Sony Green Partner / SS-00259', complianceText: 'Laboratory-grade hazardous substance management. Export clearance for EU, Japan, and North America.', productTitle: 'Built to be handled.', productMuted: 'Made to be kept.', formLine: '01 / Packaging model', formVolume: '02 / Estimated volume', estimate: 'Live logistics estimate', shipping: 'Estimated shipping volume', weight: 'Estimated gross weight', dispatch: 'Rapid sample dispatch', value: 'Factory Direct Pricing · 0% Middleman Markup · Official CAD & DFM Feedback in 12 Hours', send: 'Send inquiry', sent: 'Inquiry received — we’ll reply from the factory within 12 hours.', footer: 'Dongguan Xinhui Plastic & Packaging Factory Co., Ltd.' },
  zh: { nav: ['工程能力', 'SS-00259 标准', '产品目录', '全球供应'], cta: '索取样品套装', eyebrow: '01 / 行业基准', hero: '光学级', heroMuted: '注塑成型。', intro: '为全球媒体与收藏品而造。24 年零刮痕模具工艺、负责任的材料合规，以及源头工厂直供。', sample: '领取免费样品包', catalog: '探索模具目录', standard: '合规不是标签。', global: '而是基准。', rfq: '03 / 询价终端', quote: '让我们\n做出第一个。', contact: '工厂联系方式', address: '中国广东省东莞市黄江镇板湖旧街 2 号', email: 'ngkeihing@126.com', phone: '+86 139 0303 5533', metricLabels: ['模具经验年限', '供应国家', '毫米公差', '每月产能'], complianceTitle: 'Sony Green Partner / SS-00259', complianceText: '实验室级有害物质管理，满足欧盟、日本及北美出口要求。', productTitle: '经得起握持。', productMuted: '值得被珍藏。', formLine: '01 / 包装型号', formVolume: '02 / 预估数量', estimate: '实时物流预估', shipping: '预估运输体积', weight: '预估毛重', dispatch: '快速寄样时间', value: '工厂直供价 · 0% 中间商加价 · 12 小时内提供官方 CAD 与 DFM 反馈', send: '发送询价', sent: '询价已收到 — 工厂将在 12 小时内回复。', footer: '东莞市新辉盒带厂有限公司' },
}
const products = [
  ['01', 'Standard Jewel Case', '10.4 mm / GPPS', 'High-gloss GPPS · engineered book-fold hinge · 1,000+ cycle fatigue resistance', Layers3],
  ['02', 'Slimline Case', '5.2 mm / PP', 'Ultra-thin space-saving optical tray · optimized for premium media collections', Sparkles],
  ['03', 'Multi-Disc Housing', 'Dual / Quad Tray', 'Modular disc trays · SD / USB integrated media organizers · export ready', Cpu],
  ['04', 'Collectible Brick', 'Optical-grade / GPPS', 'Acrylic-equivalent clarity · scratch-resistant snap locks for card markets', Zap],
]
const compliance = [['Cd', '< 5ppm'], ['Pb', 'Zero Added'], ['Hg', 'Zero Added'], ['Cr⁶⁺', 'Zero Added'], ['PBB / PBDE', 'Free'], ['RoHS 2.0', '& REACH'], ['BPA', 'Free']]
const logistics: Record<string, Record<string, [string, string]>> = { 'Standard Jewel Case': { '2,000': ['1.8 CBM', '240 kg'], '10,000': ['9.0 CBM', '1,200 kg'], '50,000': ['45 CBM', '6,000 kg'], '200,000+': ['180+ CBM', '24,000+ kg'] }, 'Slimline Case': { '2,000': ['1.1 CBM', '150 kg'], '10,000': ['5.5 CBM', '750 kg'], '50,000': ['27.5 CBM', '3,750 kg'], '200,000+': ['110+ CBM', '15,000+ kg'] }, 'Multi-Disc Housing': { '2,000': ['3.0 CBM', '420 kg'], '10,000': ['15 CBM', '2,100 kg'], '50,000': ['75 CBM', '10,500 kg'], '200,000+': ['300+ CBM', '42,000+ kg'] }, 'Collectible Brick': { '2,000': ['2.4 CBM', '310 kg'], '10,000': ['12 CBM', '1,550 kg'], '50,000': ['60 CBM', '7,750 kg'], '200,000+': ['240+ CBM', '31,000+ kg'] } }

export default function Page() {
  const [lang, setLang] = useState<Lang>('en'); const t = copy[lang]; const [menuOpen, setMenuOpen] = useState(false); const [model, setModel] = useState('Standard Jewel Case'); const [volume, setVolume] = useState('10,000'); const [sent, setSent] = useState(false); const [line, setLine] = useState('Standard Jewel Case')
  const estimate = logistics[model][volume]
  return <main className="min-h-screen overflow-hidden bg-[#09090b] text-[#fafafa] selection:bg-sky-400 selection:text-black"><div className="pointer-events-none fixed inset-0 z-0 opacity-[0.035] [background-image:linear-gradient(rgba(255,255,255,.8)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.8)_1px,transparent_1px)] [background-size:64px_64px]" />
    <nav className="fixed left-1/2 top-4 z-50 flex w-[calc(100%-32px)] max-w-[1240px] -translate-x-1/2 items-center justify-between rounded-full border border-white/10 bg-zinc-950/70 px-4 py-3 backdrop-blur-xl md:px-5"><a href="#top" className="flex items-center gap-3 text-sm font-semibold"><span className="grid size-7 place-items-center rounded-full bg-white text-[10px] text-black">X</span><span>XINHUI <span className="font-normal text-zinc-500">· est. 2002</span></span></a><div className="hidden items-center gap-7 text-[11px] uppercase tracking-[0.15em] text-zinc-400 lg:flex">{t.nav.map((n, i) => <a key={n} href={['#engineering', '#standard', '#tooling', '#global'][i]} className="transition-colors hover:text-white">{n}</a>)}</div><div className="flex items-center gap-2"><div className="flex rounded-full border border-white/10 p-0.5 text-[10px] font-bold"><button onClick={() => setLang('en')} className={`rounded-full px-2 py-1 ${lang === 'en' ? 'bg-white text-black' : 'text-zinc-500'}`}>EN</button><button onClick={() => setLang('zh')} className={`rounded-full px-2 py-1 ${lang === 'zh' ? 'bg-white text-black' : 'text-zinc-500'}`}>中文</button></div><a href="#quote" className="hidden items-center gap-2 rounded-full bg-sky-400 px-4 py-2 text-[11px] font-bold uppercase tracking-wider text-sky-950 sm:flex">{t.cta}<ArrowUpRight size={14} /></a><button aria-label="打开菜单" onClick={() => setMenuOpen(!menuOpen)} className="grid size-9 place-items-center rounded-full border border-white/10 text-zinc-300 sm:hidden">{menuOpen ? <X size={17} /> : <Menu size={17} />}</button></div>{menuOpen && <div className="absolute right-0 top-14 flex w-56 flex-col gap-4 rounded-2xl border border-white/10 bg-zinc-900 p-5 text-sm text-zinc-300 shadow-2xl sm:hidden">{t.nav.slice(0, 3).map((n, i) => <a key={n} href={['#engineering', '#standard', '#tooling'][i]} onClick={() => setMenuOpen(false)}>{n}</a>)}</div>}</nav>
    <section id="top" className="relative z-10 mx-auto flex min-h-[820px] max-w-[1240px] flex-col justify-center px-5 pb-20 pt-36 md:px-10 lg:min-h-[900px]"><div className="max-w-4xl"><div className="mb-8 inline-flex items-center gap-2 rounded-full border border-sky-400/25 bg-sky-400/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-sky-300"><span className="size-1.5 animate-pulse rounded-full bg-sky-300" /> Certified Sony Green Partner · UKAS · 5M/Mo</div><h1 className="max-w-5xl whitespace-pre-line text-5xl font-medium leading-[0.98] tracking-[-0.07em] md:text-7xl lg:text-[104px]">{t.hero}<br /><span className="text-zinc-500">{t.heroMuted}</span></h1><p className="mt-9 max-w-xl text-base leading-7 text-zinc-400 md:text-lg">{t.intro}</p><div className="mt-9 flex flex-wrap items-center gap-3"><a href="#quote" className="flex items-center gap-3 rounded-full bg-white px-5 py-3 text-sm font-semibold text-black">{t.sample}<ArrowUpRight size={16} /></a><a href="#tooling" className="flex items-center gap-3 rounded-full border border-white/15 px-5 py-3 text-sm text-zinc-300">{t.catalog}<FileDown size={16} /></a></div></div><div className="mt-20 grid grid-cols-2 gap-8 border-t border-white/10 pt-6 md:flex md:gap-20"><Metric value="24" label={t.metricLabels[0]} /><Metric value="60+" label={t.metricLabels[1]} /><Metric value="±0.05" label={t.metricLabels[2]} /><Metric value="5M+" label={t.metricLabels[3]} /></div><div className="absolute bottom-10 right-5 hidden h-[330px] w-[330px] md:block lg:right-16 lg:h-[390px] lg:w-[390px]"><div className="absolute inset-8 rounded-full border border-sky-300/20 shadow-[0_0_100px_rgba(56,189,248,.15)]" /><div className="case-visual absolute left-1/2 top-1/2 h-56 w-40 -translate-x-1/2 -translate-y-1/2 -rotate-[9deg] rounded-xl border border-white/35 bg-gradient-to-br from-white/20 via-sky-100/5 to-transparent shadow-[12px_20px_40px_rgba(0,0,0,.6),inset_2px_2px_20px_rgba(255,255,255,.2)]"><div className="absolute inset-5 rounded-md border border-white/15" /><div className="absolute bottom-5 left-5 right-5 h-8 rounded border border-white/10 bg-white/5" /></div></div></section>
    <section id="engineering" className="relative z-10 border-y border-white/10 bg-zinc-950/60"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-24 md:px-10 lg:grid-cols-[.8fr_1.2fr] lg:py-32"><div><Eyebrow>{t.eyebrow}</Eyebrow><h2 className="mt-5 max-w-md text-4xl leading-[1.05] tracking-[-0.05em] md:text-6xl">{t.standard}<br /><span className="text-zinc-500">{t.global}</span></h2><p className="mt-6 max-w-sm leading-7 text-zinc-400">{t.complianceText}</p></div><div id="standard" className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2"><div className="bg-zinc-950 p-7 sm:col-span-2"><div className="flex items-start justify-between"><div><ShieldCheck className="text-sky-300" size={22} /><h3 className="mt-5 text-xl font-medium">{t.complianceTitle}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-zinc-500">{t.complianceText}</p></div><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[9px] uppercase tracking-widest text-emerald-300">Verified</span></div><div className="mt-8 flex flex-wrap gap-2">{compliance.map(([a, b]) => <span key={a} className="rounded-full border border-sky-300/20 bg-sky-300/5 px-3 py-2 font-mono text-[10px] text-sky-200">{a} {b}</span>)}</div></div><Feature icon={Factory} title={lang === 'en' ? 'Precision tooling' : '精密模具'} text={lang === 'en' ? 'Cleanroom molding · robotic pick & place · anti-static de-ionizing curtains.' : '洁净注塑 · 机械手取件 · 防静电离子风幕。'} /><Feature icon={Globe2} title={lang === 'en' ? 'Factory backbone' : '工厂基础能力'} text={lang === 'en' ? 'Founded 2002 · 5,000,000+ monthly capacity · direct export to 60+ countries.' : '成立于 2002 年 · 每月 5,000,000+ 产能 · 直供全球 60+ 国家。'} /></div></div></section>
    <section id="tooling" className="relative z-10 mx-auto max-w-[1240px] px-5 py-24 md:px-10 lg:py-32"><div><Eyebrow>02 / Product architecture</Eyebrow><h2 className="mt-5 text-4xl tracking-[-0.05em] md:text-6xl">{t.productTitle}<br /><span className="text-zinc-500">{t.productMuted}</span></h2></div><div className="mt-14 grid gap-3 md:grid-cols-2">{products.map(([number, title, meta, detail, Icon]) => <article key={number as string} className="group rounded-2xl border border-white/10 bg-zinc-900/60 p-6 md:p-8"><div className="flex items-start justify-between"><span className="font-mono text-xs text-zinc-600">{number as string}</span><Icon size={22} className="text-zinc-500 group-hover:text-sky-300" /></div><div className="mt-16 flex items-end justify-between gap-4"><div><h3 className="text-2xl tracking-tight">{title as string}</h3><p className="mt-2 font-mono text-[10px] uppercase tracking-widest text-sky-300">{meta as string}</p></div></div><p className="mt-5 max-w-md text-sm leading-6 text-zinc-500">{detail as string}</p></article>)}</div></section>
    <section id="quote" className="relative z-10 border-t border-white/10 bg-zinc-950"><div className="mx-auto grid max-w-[1240px] gap-12 px-5 py-24 md:px-10 lg:grid-cols-[.7fr_1.3fr] lg:py-32"><div><Eyebrow>{t.rfq}</Eyebrow><h2 className="mt-5 whitespace-pre-line text-4xl tracking-[-0.05em] md:text-6xl">{t.quote}</h2><p className="mt-6 max-w-sm text-sm leading-7 text-zinc-400">{t.value}</p><div className="mt-10 flex items-center gap-3 text-xs text-zinc-500"><span className="grid size-8 place-items-center rounded-full border border-white/10 text-sky-300">24</span>{t.metricLabels[0]}</div></div><form onSubmit={(e) => { e.preventDefault(); setSent(true) }} className="rounded-2xl border border-white/10 bg-zinc-900/60 p-6 md:p-9"><label className="text-xs text-zinc-500">{t.formLine}</label><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{Object.keys(logistics).map((name) => <button type="button" key={name} onClick={() => { setModel(name); setLine(name) }} className={`rounded-lg border px-3 py-3 text-left text-xs ${line === name ? 'border-sky-300 bg-sky-300/10 text-sky-200' : 'border-white/10 text-zinc-500'}`}>{name}</button>)}</div><label className="mt-8 block text-xs text-zinc-500">{t.formVolume}</label><div className="relative mt-3"><select value={volume} onChange={(e) => setVolume(e.target.value)} className="w-full appearance-none rounded-lg border border-white/10 bg-zinc-950 px-4 py-3 text-sm text-white outline-none">{['2,000', '10,000', '50,000', '200,000+'].map((v) => <option key={v}>{v}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-3.5 text-zinc-500" size={16} /></div><div className="mt-8 rounded-xl border border-sky-300/20 bg-sky-300/5 p-5"><p className="text-[10px] uppercase tracking-widest text-sky-300">{t.estimate}</p><div className="mt-5 grid grid-cols-3 gap-3"><Stat label={t.shipping} value={estimate[0]} /><Stat label={t.weight} value={estimate[1]} /><Stat label={t.dispatch} value="24h–48h" /></div></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-black">{sent ? <><Check size={16} /> {t.sent}</> : <>{t.send} <ArrowUpRight size={16} /></>}</button></form></div></section>
    <footer id="global" className="relative z-10 border-t border-white/10"><div className="mx-auto flex max-w-[1240px] flex-col gap-10 px-5 py-12 md:flex-row md:items-end md:justify-between md:px-10"><div><p className="text-sm font-semibold">{t.footer}</p><p className="mt-5 max-w-sm text-xs leading-6 text-zinc-500">{t.address}</p></div><div className="flex flex-col gap-3 text-left text-xs text-zinc-400 md:text-right"><a href={`mailto:${t.email}`} className="flex items-center gap-2 hover:text-sky-300"><Mail size={14} /> {t.email}</a><a href={`tel:${t.phone.replaceAll(' ', '')}`} className="flex items-center gap-2 hover:text-sky-300"><Phone size={14} /> {t.phone}</a><p className="text-zinc-600">© 2026 Xinhui · RoHS · REACH · Sony GP</p></div></div></footer>
  </main>
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-sky-300">{children}</p> }
function Metric({ value, label }: { value: string; label: string }) { return <div><p className="text-2xl tracking-tight md:text-3xl">{value}</p><p className="mt-1 text-[10px] uppercase tracking-widest text-zinc-600">{label}</p></div> }
function Feature({ icon: Icon, title, text }: { icon: typeof Factory; title: string; text: string }) { return <div className="bg-zinc-950 p-7"><Icon size={20} className="text-sky-300" /><h3 className="mt-6 text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p></div> }
function Stat({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] leading-4 text-zinc-500">{label}</p><p className="mt-2 font-mono text-sm text-white">{value}</p></div> }


