import { NextResponse } from 'next/server'

const recipients = ['jimwyj5@gmail.com', 'ngkeihing@126.com']

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character)
}

export async function POST(request: Request) {
  try {
    const body = await request.json()
    const fields = {
      email: String(body.email ?? '').trim(),
      destination: String(body.destination ?? '').trim(),
      quantity: String(body.quantity ?? '').trim(),
      estimatedCbm: String(body.estimatedCbm ?? '').trim(),
      estimatedWeight: String(body.estimatedWeight ?? '').trim(),
      note: String(body.note ?? '').trim(),
    }

    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json({ error: 'Email service is not configured.' }, { status: 503 })
    }
    if (!fields.email || !fields.destination || !fields.quantity) {
      return NextResponse.json({ error: 'Email, destination, and quantity are required.' }, { status: 400 })
    }

    const timestamp = new Intl.DateTimeFormat('en-GB', { dateStyle: 'full', timeStyle: 'long', timeZone: 'Asia/Shanghai' }).format(new Date())
    const rows = [
      ['CONTACT EMAIL', fields.email],
      ['DESTINATION', fields.destination],
      ['QUANTITY', fields.quantity],
      ['ESTIMATED CBM', fields.estimatedCbm || '—'],
      ['ESTIMATED GROSS WEIGHT', fields.estimatedWeight || '—'],
      ['PROJECT NOTE', fields.note || '—'],
      ['RECEIVED AT', timestamp],
    ]
    const html = `<div style="background:#111418;color:#f4f1e8;padding:32px;font-family:Arial,sans-serif"><div style="max-width:720px;margin:auto"><p style="color:#f26b38;font-size:11px;letter-spacing:2px">SUN LIGHT / RFQ TERMINAL</p><h1 style="font-size:28px;font-weight:500;margin:12px 0 28px">New manufacturing inquiry</h1><table style="width:100%;border-collapse:collapse;font-size:13px">${rows.map(([label, value]) => `<tr><td style="width:35%;padding:14px 10px;border-top:1px solid #3a4045;color:#8f989d;letter-spacing:1px">${escapeHtml(label)}</td><td style="padding:14px 10px;border-top:1px solid #3a4045;color:#ffffff">${escapeHtml(value)}</td></tr>`).join('')}</table><p style="color:#8f989d;font-size:11px;margin-top:28px">Generated by SUN LIGHT CASSETTE MANUFACTURING LIMITED.</p></div></div>`

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from: 'Sun Light RFQ Terminal <onboarding@resend.dev>', to: recipients, subject: `RFQ inquiry · ${fields.quantity} units · ${fields.destination}`, html }),
    })

    if (!response.ok) {
      return NextResponse.json({ error: 'Email delivery failed.' }, { status: 502 })
    }
    return NextResponse.json({ ok: true })
  } catch {
    return NextResponse.json({ error: 'Invalid inquiry payload.' }, { status: 400 })
  }
}
